import {NextResponse} from 'next/server'; import {q,tx} from '../../../lib/db'; import {eventKey,timingSafeText} from '../../../lib/security'; import {bookAppointment} from '../../../lib/booking';
function authorised(req:Request){const expected=process.env.VAPI_WEBHOOK_BEARER_TOKEN||''; const auth=req.headers.get('authorization')||''; const got=auth.replace(/^Bearer\s+/i,''); return !!expected&&timingSafeText(expected,got)}
function leadIdFrom(message:any){return message?.call?.assistantOverrides?.variableValues?.leadId || message?.call?.assistant?.variableValues?.leadId || message?.assistantOverrides?.variableValues?.leadId || null}
export async function POST(req:Request){if(!authorised(req))return NextResponse.json({error:'Unauthorized'},{status:401}); const raw=await req.text(); let body:any; try{body=JSON.parse(raw)}catch{return NextResponse.json({error:'Invalid JSON'},{status:400})} const message=body.message||body; const key=eventKey(raw); const existing=(await q<any>(`SELECT response,processed_at FROM webhook_events WHERE provider='vapi' AND event_key=$1`,[key])).rows[0]; if(existing?.processed_at&&existing.response)return NextResponse.json(existing.response);
 await q(`INSERT INTO webhook_events(provider,event_key,payload) VALUES('vapi',$1,$2::jsonb) ON CONFLICT DO NOTHING`,[key,raw]); const providerCallId=message?.call?.id||message?.callId||null; const hintedLeadId=leadIdFrom(message); const call=(providerCallId?(await q<any>(`SELECT c.*,l.organization_id FROM calls c JOIN leads l ON l.id=c.lead_id WHERE c.provider_call_id=$1 LIMIT 1`,[providerCallId])).rows[0]:null); const leadId=call?.lead_id||hintedLeadId; const organizationId=call?.organization_id||(leadId?(await q<any>(`SELECT organization_id FROM leads WHERE id=$1`,[leadId])).rows[0]?.organization_id:null);
 let response:any={received:true};
 if(message.type==='tool-calls'||message.type==='tool-calls-result-request'){const list=message.toolCallList||message.toolCalls||[]; const results=[]; for(const t of list){const name=t.name||t.function?.name; const id=t.id||t.toolCallId; const params=t.parameters||t.function?.arguments||{}; try{if(!leadId||!organizationId)throw new Error('Lead context unavailable'); if(name==='qualifyLead'){await q(`UPDATE leads SET status='qualified',notes=concat_ws(E'\\n',notes,$1),updated_at=now() WHERE id=$2 AND organization_id=$3`,[params.notes||null,leadId,organizationId]); results.push({name,toolCallId:id,result:JSON.stringify({ok:true})});} else if(name==='bookAppointment'){const a=await bookAppointment(organizationId,leadId,params.appointmentAt,Number(params.durationMinutes||30)); results.push({name,toolCallId:id,result:JSON.stringify({ok:true,appointmentAt:a.starts_at})});} else if(name==='doNotContact'){await q(`UPDATE leads SET status='do_not_contact',do_not_contact=true,updated_at=now() WHERE id=$1 AND organization_id=$2`,[leadId,organizationId]); results.push({name,toolCallId:id,result:JSON.stringify({ok:true})});} else {results.push({name,toolCallId:id,result:JSON.stringify({ok:false,error:'Unsupported tool'})});}}catch(e:any){results.push({name,toolCallId:id,result:JSON.stringify({ok:false,error:String(e?.message||e)})});}}
 response={results};
 } else if(message.type==='status-update'&&providerCallId){await q(`UPDATE calls SET status=$1,started_at=COALESCE(started_at,CASE WHEN $1 IN ('in-progress','ringing') THEN now() END) WHERE provider_call_id=$2`,[message.status||'unknown',providerCallId]);
 } else if(message.type==='end-of-call-report'&&leadId&&organizationId){const summary=message.summary||message.analysis?.summary||''; const outcome=message.analysis?.structuredData?.outcome||message.analysis?.successEvaluation||null; await tx(async c=>{if(providerCallId)await c.query(`UPDATE calls SET status='ended',ended_at=now(),summary=$1,outcome=$2 WHERE provider_call_id=$3`,[summary,outcome,providerCallId]); await c.query(`UPDATE leads SET last_contact_at=now(),notes=concat_ws(E'\\n',notes,$1),status=CASE WHEN $2='qualified' THEN 'qualified' WHEN $2='booked' THEN 'booked' ELSE status END,updated_at=now() WHERE id=$3 AND organization_id=$4`,[summary||null,outcome,leadId,organizationId]);});}
 await q(`UPDATE webhook_events SET processed_at=now(),response=$2::jsonb WHERE provider='vapi' AND event_key=$1`,[key,JSON.stringify(response)]); return NextResponse.json(response);}
